export const cars = [
    {
      id: 1,
      brand: "Tesla",
      model: "Model S Plaid",
      type: "Электрический",
      body: "Седан",
      state: "Новое",
      drive: "Полный",
      power: "1020 л.с.",
      range: 637,
      speed: 322,
      acceleration: 2.1,
      weight: 2162,
      price: 89990,
      image: "/Tesla-modul-x.png", // Убедись, что фото в public/cars/
      bestFor: "Скорость и технологии"
    },
    {
      id: 2,
      brand: "Volkswagen",
      model: "ID.6 Crozz",
      type: "Электрический",
      body: "Внедорожник",
      state: "Новое",
      drive: "Задний",
      power: "204 л.с.",
      range: 601,
      speed: 160,
      acceleration: 9.1,
      weight: 2280,
      price: 45000,
      image: "/volkswagen-crozz .png",
      bestFor: "Семья и город"
    },
    {
      id: 3,
      brand: "BMW",
      model: "M4 Competition",
      type: "Бензин",
      body: "Купе",
      state: "С пробегом",
      drive: "Задний",
      power: "510 л.с.",
      range: 500,
      speed: 290,
      acceleration: 3.9,
      weight: 1800,
      price: 78000,
      image: "/BMW_M4.png",
      bestFor: "Спорт и драйв"
    },
    {
        id: 4,
        brand: "BMW",
        model: "M5 Competition",
        type: "Бензин",
        body: "Седан",
        state: "С пробегом",
        drive: "Полный (AWD)",
        power: "625 л.с.",
        range: 500,
        speed: 305,
        acceleration: 3.3,
        weight: 1895,
        price: 78000,
        image: "/Bmw-M5-Competition.png",
        bestFor: "Спорт и быстрые поездки"
      },
      {
        id: 5,
        brand: "Tesla",
        model: "Model 3 Performance",
        type: "Электро",
        body: "Седан",
        state: "Новый",
        drive: "Полный (AWD)",
        power: "1020 л.с.",
        range: 637,
        speed: 322,
        acceleration: 2.1,
        weight: 2162,
        price: 110000,
        image: "/Tesla Model 3 Performance.png",
        bestFor: "Технологии и скорость"
      },
      {
        id: 6,
        brand: "Audi",
        model: "RS7",
        type: "Бензин",
        body: "Седан",
        state: "Новый",
        drive: "Полный (AWD)",
        power: "600 л.с.",
        range: 480,
        speed: 305,
        acceleration: 3.6,
        weight: 2140,
        price: 120000,
        image: "/Audi-RS7.png",
        bestFor: "Комфорт и спорт"
      },
      {
        id: 7,
        brand: "Mercedes",
        model: "AMG GT 63",
        type: "Бензин",
        body: "Купе",
        state: "Новый",
        drive: "Полный (AWD)",
        power: "639 л.с.",
        range: 470,
        speed: 315,
        acceleration: 3.2,
        weight: 2045,
        price: 140000,
        image: "/Mercedes-AMG_GT63.png",
        bestFor: "Люкс и мощность"
      },
      {
        id: 8,
        brand: "Porsche",
        model: "Taycan Turbo S",
        type: "Электро",
        body: "Седан",
        state: "Новый",
        drive: "Полный (AWD)",
        power: "761 л.с.",
        range: 450,
        speed: 260,
        acceleration: 2.8,
        weight: 2295,
        price: 150000,
        image: "/Porsche-Taycan.png",
        bestFor: "Электро спорт"
      },
      {
        id: 9,
        brand: "Lamborghini",
        model: "Huracan EVO",
        type: "Бензин",
        body: "Купе",
        state: "Новый",
        drive: "Полный (AWD)",
        power: "640 л.с.",
        range: 400,
        speed: 325,
        acceleration: 2.9,
        weight: 1422,
        price: 250000,
        image: "/Lamborghini-Huracan.png",
        bestFor: "Суперкар"
      },
      {
        id: 10,
        brand: "Ferrari",
        model: "Roma",
        type: "Бензин",
        body: "Купе",
        state: "Новый",
        drive: "Задний (RWD)",
        power: "620 л.с.",
        range: 450,
        speed: 320,
        acceleration: 3.4,
        weight: 1570,
        price: 220000,
        image: "/Ferrari-Roma.png",
        bestFor: "Люкс и спортивные поездки"
      },
      {
        id: 11,
        brand: "McLaren",
        model: "Artura",
        type: "Гибрид",
        body: "Купе",
        state: "Новый",
        drive: "Задний (RWD)",
        power: "680 л.с.",
        range: 500,
        speed: 330,
        acceleration: 3.0,
        weight: 1498,
        price: 230000,
        image: "/McLaren-Artura.png",
        bestFor: "Суперкар и трек"
      },
      {
        id: 12,
        brand: "Nissan",
        model: "Z",
        type: "Бензин",
        body: "Купе",
        state: "Новый",
        drive: "Задний (RWD)",
        power: "405 л.с.",
        range: 480,
        speed: 250,
        acceleration: 4.5,
        weight: 1610,
        price: 45000,
        image: "/Nissan-Z.png",
        bestFor: "Спорт и дрифт"
      },
      {
        id: 13,
        brand: "Toyota",
        model: "GR Supra",
        type: "Бензин",
        body: "Купе",
        state: "Новый",
        drive: "Задний (RWD)",
        power: "382 л.с.",
        range: 520,
        speed: 250,
        acceleration: 4.1,
        weight: 1495,
        price: 52000,
        image: "/Toyota-GR-Supra.png",
        bestFor: "Спорт и драйв"
      }
    
  ];